/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/common/AppLayout.vue')['default']
    DataIntervalSelector: typeof import('./src/components/monitoring/DataIntervalSelector.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    InterfaceInfoCard: typeof import('./src/components/dashboard/InterfaceInfoCard.vue')['default']
    InterfaceSelector: typeof import('./src/components/dashboard/InterfaceSelector.vue')['default']
    NetworkSpeedChart: typeof import('./src/components/monitoring/NetworkSpeedChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedCard: typeof import('./src/components/dashboard/SpeedCard.vue')['default']
    StatusTag: typeof import('./src/components/common/StatusTag.vue')['default']
    ThemeSwitch: typeof import('./src/components/common/ThemeSwitch.vue')['default']
    TimeIntervalSelector: typeof import('./src/components/monitoring/TimeIntervalSelector.vue')['default']
    TrafficStatsCard: typeof import('./src/components/dashboard/TrafficStatsCard.vue')['default']
    TrafficStatsChart: typeof import('./src/components/monitoring/TrafficStatsChart.vue')['default']
  }
}
